### ISSUE TITLE
Building an RPM

### ISSUE THREAD

**Issue by bharnden** [USNavalResearchLaboratory/ospf-mdr#10]
I did some work to try and build RPMs on Rocky Linux 8 and appear to have had success, I will still need to validate an install.

I followed these steps to build, after trying to determine all the various dependencies needed.
```shell
git clone https://github.com/USNavalResearchLaboratory/ospf-mdr.git
cd ospd-mdr
./bootstrap.sh
./configure
make -f quagga.rpm.mk
```

I did need to modify the spec file slightly to avoid error, not sure if this is something that should be updated in the repo or changed differently than I have.

```diff
diff --git a/redhat/quagga.spec.in b/redhat/quagga.spec.in
index 8230917..b4ae9cb 100644
--- a/redhat/quagga.spec.in
+++ b/redhat/quagga.spec.in
@@ -446,7 +446,7 @@ rm -rf $RPM_BUILD_ROOT
 %doc doc/quagga.html
 %doc doc/quagga.pdf
 %doc doc/mpls
-%doc ChangeLog INSTALL NEWS README REPORTING-BUGS SERVICES TODO RELEASE_NOTES.MobileRouting
+%doc ChangeLog INSTALL.quagga.txt NEWS README REPORTING-BUGS SERVICES TODO RELEASE_NOTES.MobileRouting
 %if 0%{?quagga_user:1}
 %dir %attr(751,%quagga_user,%quagga_user) %{_sysconfdir}
 %dir %attr(750,%quagga_user,%quagga_user) /var/log/quagga 
@@ -457,7 +457,7 @@ rm -rf $RPM_BUILD_ROOT
 %dir %attr(755,root,root) /usr/share/info
 %dir %attr(750,root,root) /var/run/quagga
 %endif
-%{_infodir}/*info*
+#%{_infodir}/*info*
 %{_mandir}/man*/*
 %{_sbindir}/zebra
 %{_sbindir}/ospfd
```

**Comment by bharnden** [comment]
Appears I must have not had some expected dependencies at some part of the build, as I was trying to figure things out. Looks to not be an issue for now.

**Comment by b00ga** [comment]
Just a quick acknowledgement. When you run configure, it will look for rpm tools (basically, you need to "dnf install rpm-build"). If they are not detected, the RPM make target will not be enabled.

**Comment by bharnden** [comment]
Ya, I have or had all that. But, I may just not have had a clean path at the time. I set it up within a docker build step now. I was hoping to get insight into what exactly I should be doing as a clean build path.

Depending on the source and cloning the repo all the time is unideal. I have something that works now technically, but the way I am getting there feels really wrong.
